# (실습) 넘파이 어레이

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

## numpy 모듈

**문제 1**

아래 코드를 설명하라.

In [2]:
import numpy as np

`코드설명`: 넘파이를 불러오는 함수

아래 코드는 수정하지 마세요!!!

In [3]:
np.__version__

'1.26.4'

**문제 2**

아래 코드의 기능을 설명하라

In [5]:
np.random.seed(42)

`코드설명`: 램던시디 42로 지정

**문제 3**

부동소수점으로 구성된 어레이의 항목은 기본적으로 소수점 이하 8자리까지 출력한다.

In [9]:
np.random.seed(42)
Z = np.random.random((40,40))
Z 

array([[0.37454012, 0.95071431, 0.73199394, ..., 0.09767211, 0.68423303,
        0.44015249],
       [0.12203823, 0.49517691, 0.03438852, ..., 0.07404465, 0.35846573,
        0.11586906],
       [0.86310343, 0.62329813, 0.33089802, ..., 0.18657006, 0.892559  ,
        0.53934224],
       ...,
       [0.81783422, 0.12020906, 0.5444891 , ..., 0.89803055, 0.2434823 ,
        0.92703454],
       [0.06026739, 0.93443603, 0.35162269, ..., 0.41102847, 0.8398613 ,
        0.90002312],
       [0.35342138, 0.23687056, 0.78052552, ..., 0.07941937, 0.08565825,
        0.89419087]])

`np.set_printoptions()` 의 기능을 다음 두 개의 예를 이용하여 설명하라.

In [10]:
np.set_printoptions(precision=4)

In [11]:
Z

array([[0.3745, 0.9507, 0.732 , ..., 0.0977, 0.6842, 0.4402],
       [0.122 , 0.4952, 0.0344, ..., 0.074 , 0.3585, 0.1159],
       [0.8631, 0.6233, 0.3309, ..., 0.1866, 0.8926, 0.5393],
       ...,
       [0.8178, 0.1202, 0.5445, ..., 0.898 , 0.2435, 0.927 ],
       [0.0603, 0.9344, 0.3516, ..., 0.411 , 0.8399, 0.9   ],
       [0.3534, 0.2369, 0.7805, ..., 0.0794, 0.0857, 0.8942]])

In [12]:
np.set_printoptions(precision=6)

In [13]:
Z

array([[0.37454 , 0.950714, 0.731994, ..., 0.097672, 0.684233, 0.440152],
       [0.122038, 0.495177, 0.034389, ..., 0.074045, 0.358466, 0.115869],
       [0.863103, 0.623298, 0.330898, ..., 0.18657 , 0.892559, 0.539342],
       ...,
       [0.817834, 0.120209, 0.544489, ..., 0.898031, 0.243482, 0.927035],
       [0.060267, 0.934436, 0.351623, ..., 0.411028, 0.839861, 0.900023],
       [0.353421, 0.236871, 0.780526, ..., 0.079419, 0.085658, 0.894191]])

`코드설명`: 부동소수점 정밀도를 4로 지정해서 소수점 이하 4자리만 보여주고 
        부동소수번 정밀도를 6으로 지정하여 소수점 이하 6자리만 보여줌

아래 코드는 기본 옵션값으로 되돌린다. 수정하지 마세요.

In [14]:
np.set_printoptions(precision=8)

## 1차원 어레이

**문제 1**

크기가 10이고 모든 항목이 0인 1차원 어레이를
변수 `Z`가 가리키도록 하라.
단, `np.zeros()` 함수를 반드시 이용한다.

In [15]:
Z = np.zeros(10)


In [17]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

아래 코드는 수정하지 마세요!!!

In [16]:
assert (Z == np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])).all()

**문제 2**

변수 `Z`가 10에서 49까지의 정수 중에서 짝수로만 구성된 1차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수를 반드시 이용한다.

In [18]:
Z = np.arange(10,50,2)
Z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
                        44, 46, 48])).all()

**문제 3**

변수 `Z`가 아래와 같이 선언되었다.

In [19]:
Z = np.array([2, 3, 1, 0, 4])
Z

array([2, 3, 1, 0, 4])

변수 `Z`의 항목을 정렬하라.
단, sort() 메서드를 활용한다.

In [13]:
import numpy as np

Z = np.array([2, 3, 1, 0, 4])
from numpy.testing import assert_array_equal
assert_array_equal(np.sort(Z), np.arange(5))

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.arange(5)).all()

**문제 4**

변수 `Z`가 크기 30이며 무작위로 생성된 1차원 어레이를 가리키도록 하라.
또한 포함된 항목들의 평균값을 계산하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
`np.random.random()` 함수, `mean()` 어레이 메서드를 반드시 이용한다.

In [34]:
Z = np.random.random(30)   #0에서 29 난수 생성, 좌우를 균등하게 생성
print(Z)
Z_mean = Z.mean()

[0.96339443 0.56016818 0.93682246 0.05225788 0.41879332 0.26015779
 0.73082096 0.98129709 0.25653006 0.6541746  0.19809763 0.56533025
 0.46393249 0.97200533 0.60852727 0.34950637 0.11409578 0.15124683
 0.22531693 0.25096666 0.85061606 0.56122279 0.52339091 0.11476887
 0.86013969 0.7228143  0.06766836 0.7078351  0.54353822 0.08172535]


아래 코드는 수정하지 마세요!!!

In [35]:
assert (Z.shape == (30,))
print(f"1차원 어레이 평균값: {Z_mean}")

1차원 어레이 평균값: 0.4915720663306763


**문제 5**

1차원 어레이가 다음과 같이 주어졌다.

In [36]:
Z = np.arange(1, 4)

(1) 아래 표현식의 계산 결과를 설명하라.

In [37]:
Z*Z

array([1, 4, 9])

`코드설명`: arry([1,4,9])
Z[0] * Z[0]= 1*1=1
Z[1] * Z[1] = 2*2=4
Z[2] * Z[2] = 3*3=9

(2) 아래 표현식의 계산 결과를 설명하라.

In [38]:
Z**Z

array([ 1,  4, 27])

`코드설명`: arrt([1,4,27])
Z[0]**Z[0] = 1**1 = 1
Z[1]**Z[1] = 2**2 = 4
Z[2]**Z[2] = 3**3 = 27

(3) 아래 표현식의 계산 결과를 설명하라.

In [39]:
Z < -Z

array([False, False, False])

`코드설명`: array([False, False, False])
Z가 -Z보다 크기 떄문에 전부 False 가 나옴옴

(4) 아래 표현식의 계산 결과를 설명하라.

In [40]:
Z/1/1

array([1., 2., 3.])

`코드설명`: array([1., 2., 3.]) 나눗셈 2번 실행

**문제 6**

변수 `Z`가 아래 모양의 어레이를 가리키도록 하라.
단, `np.linspace()` 함수와 `endpoint` 키워드 인자를 이용한다.

```
[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
```

In [47]:
Z = np.linspace(0, 0.9, num=10, endpoint=True)
Z

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert np.isclose(Z, np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])).all()

**문제 7**

아래 코드의 실행결과를 설명하라.

In [49]:
Z = np.zeros((10,10))
print(Z)
print("%d bytes" % (Z.size * Z.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 bytes


`코드설명`: z = 100 z의 각 요소=8bytes 100*8 800 bytes   (flort64)


**문제 8**

다음 리스트에서 0이 아닌 항목들의 인덱스로 구성된 어레이를 한줄 코드로 생성하라. 
단. `np.nonzero()` 함수를 활용한다.

In [50]:
Z = [1, 2, 0, 0, 4, 0]

In [63]:
non_zeros = np.nonzero(Z)


아래 코드는 수정하지 마세요!!!

In [64]:
assert (non_zeros == np.array([0, 1, 4])).all()

**문제 9**

두 개의 1차원 어레이가 다음과 같이 주어졌다.

In [62]:
A = np.ones(3)*1
B = np.ones(3)*2

아래 코드의 실행 결과를 설명하라.

In [57]:
(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

`코드설명`: 
A = 1,1,1
B = 2,2,2
(A+B)= 3,,3,3
(-A/2)= -0.5,-0.5,-0.5
(A+B)*(-A/2)=-1.5,-1.5,-1.5

In [58]:
np.add(A,B,out=B)

array([3., 3., 3.])

`코드설명`: 

In [59]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

`코드설명`:항목별 곱셈, 곱셈, 나눗셈 실행

In [60]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

`코드설명`: A를 부정한결과를 다시A에 할당당

In [61]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

`코드설명`: A와 B를 항목별로 곱한 결과를 A에 할당 한다다

## 2차원 어레이

**문제 1**

변수 `Z`가 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [65]:
Z = np.random.random((5, 5))
Z

array([[0.45830064, 0.48469629, 0.16577454, 0.94569815, 0.84997537],
       [0.66902234, 0.46229556, 0.41176554, 0.65097347, 0.54543187],
       [0.06227311, 0.51250265, 0.80640362, 0.45923988, 0.05195658],
       [0.7862782 , 0.20136378, 0.25862083, 0.16470635, 0.33021506],
       [0.75675151, 0.51938586, 0.20488127, 0.87783008, 0.87958185]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (5, 5))
assert (Z.dtype == np.float64)

**문제 2**

변수 `Z`가 0에서 8까지의 정수로 이루어진 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `reshape()` 어레이 메서드를 반드시 이용한다.

In [66]:
Z = np.arange(9).reshape((3,3))
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])).all()

**문제 3**

변수 `Z`가 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, 2차원 어레이의 대각선 상은 1이고 나머지는 0이어야 한다.
또한 `np.eye()` 함수를 반드시 이용한다.

In [67]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all

**문제 4**

변수 `Z`가 아래와 같은 (5,5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `np.diag()` 함수의 `k` 키워드 인자를 반드시 활용한다.

```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
```

In [68]:
Z = np.diag(1+np.arange(4),k=1)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 0, 0, 0, 0],
                        [1, 0, 0, 0, 0],
                        [0, 2, 0, 0, 0],
                        [0, 0, 3, 0, 0],
                        [0, 0, 0, 4, 0]])).all()

**문제 5**

변수 `Z`가 아래와 같은 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.zeros()` 함수, `np.arange()` 함수, 2차원 어레이 덧셈을 이용한다.

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [76]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros([5,5]) * np.arange(5)
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.]])).all()

**문제 6**

아래 3x3 단위 행렬에 해당하는 2차원 어레이를 한줄 코드로 생성하라.
단, `np.eye()` 함수를 이용한다.

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [81]:
# None을 적절한 표현식으로 대체하라.
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all()

**문제 7**

무작위 수로 구성된 (5, 5) 모양의 2차원 어레이가 다음과 같다.

In [83]:
Z = np.random.random((5, 5))

변수 `Z`가 가리키는 2차원 어레이에 대해 min-max 크기조정(정규화)을 적용하라.

min-max 크기조정(정규화)은 항목의 모든 값을 아래 식을 통해 0과 1 사이의 부동소수점으로 변환한다. $max$와 $min$은 각각 최대 항목과 최소 항목을 가리킨다.

$$
\frac{x-min}{max - min}
$$

In [84]:
# None을 적절한 표현식으로 대체하라.
# 대원칙: 인공지능은 학습전에 데이터가 정규화/표준화 되어있어야 한다다
Z = (Z - Z.min()) / (Z.max() - Z.min())
Z

array([[0.92336586, 0.49915801, 0.0827081 , 0.67999511, 0.78809774],
       [0.25903355, 0.85906668, 0.91343209, 0.21477956, 0.9993462 ],
       [0.06356263, 0.13162947, 0.11187606, 0.89993784, 0.63379876],
       [0.07621216, 0.39622587, 0.5905026 , 0.        , 0.8870878 ],
       [0.79958082, 0.46826675, 0.98114276, 0.37117448, 1.        ]])

아래 코드는 수정하지 마세요!!!

In [73]:
assert (Z.max() == 1 and Z.min() == 0)

## 3차원 어레이

**문제 1**

(1) 변수 `Z`가 (3, 3, 3) 모양의 3차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [86]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random((3,3,3))
Z

array([[[0.71201402, 0.82597821, 0.10063748],
        [0.23987411, 0.14197199, 0.34794141],
        [0.45035098, 0.74882634, 0.65114758]],

       [[0.62092857, 0.35237495, 0.84144755],
        [0.47128717, 0.97910494, 0.63414214],
        [0.12626474, 0.67617756, 0.32510402]],

       [[0.6863272 , 0.06964115, 0.17488144],
        [0.85573726, 0.22717956, 0.83704113],
        [0.27927609, 0.64288191, 0.69415057]]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (3, 3, 3))
assert (Z.dtype == 'f8')

(2) `Z`에 포함된 항목들 중에서 최댓값과 최솟값의 차이를 구하라.
단, `maximum`, `mininum` 두 변수가 각각 최댓값과 최솟값을 가리키도록 하며,
`max()`와 `min()` 어레이 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
maximum = Z.max()
minimum = Z.min()

아래 코드는 수정하지 마세요!!!

In [ ]:
print(f"최댓값과 최솟값의 차이: {maximum - minimum}")

## `dtype` 종류 

**문제 1**

아래 두 코드의 실행결과를 설명하라.

In [87]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


`코드설명`: 정수형 자료형에 허용되는 비트 수에 따른 최소값과 최대값값

In [88]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


`코드설명`: 부동소수점 자료형에 허용되는 비트수에 따른 최소값과 최대값값

**문제 2**

부동소수점으로 구성된 1차원 어레이가 아래와 같이 주어졌다.

In [106]:
Z = (np.random.rand(10)*100).astype(np.float32)

변수 `Y`가 변수 `Z`가 가리키는 1차원 어레이의 dtype이 `int32`로 형변환된 1차원 어레이를 가리키도록 하라.
단, `astype()` 메서드를 이용한다.

In [108]:
# None을 적절한 표현식으로 대체하라.
Y = Z.astype(np.int32)
Y

array([91, 75, 80,  1, 96, 72, 30, 82, 28, 87])

아래 코드는 수정하지 마세요!!!

In [97]:
assert (Y.shape == (10,))
assert (Y.dtype == np.int32)

**문제 3**

변수 `Z`가 아래와 같이 무작위로 생성된 길이가 10인 1차원 어레이를 가리킨다.

In [110]:
Z = np.random.uniform(0,10,10)
Z

array([2.99919112, 7.43193199, 0.48142836, 9.02894995, 8.52263874,
       6.67804683, 5.9322157 , 8.92302498, 1.8533018 , 0.78969162])

(1) 나머지 연산자(`%`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라. 

In [111]:
# None을 적절한 표현식으로 대체하라.
Y = Z - Z%1
Y

array([2., 7., 0., 9., 8., 6., 5., 8., 1., 0.])

아래 코드는 수정하지 마세요!!!

In [99]:
assert (Y == Z.astype(np.int32)).all()

(2) 몫 연산자(`//`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [100]:
# None을 적절한 표현식으로 대체하라.
Y = Z // 1

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(3) 내림 함수 `np.floor()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라. 

In [101]:
# None을 적절한 표현식으로 대체하라.
Y = np.floor(Z)

아래 코드는 수정하지 마세요!!!

In [104]:
assert (Y == Z.astype(np.int32)).all()

(4) `np.trunc()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라. 

In [102]:
# None을 적절한 표현식으로 대체하라.
Y = np.trunc(Z)

아래 코드는 수정하지 마세요!!!

In [103]:
assert (Y == Z.astype(np.int32)).all()